Consider the below code to answer further questions:

import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [1]:
import numpy as np
list_=['1','2','3','4','5']
array_list = np.array(object=list_)

print(list_)
print(array_list)

['1', '2', '3', '4', '5']
['1' '2' '3' '4' '5']


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [2]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [3]:
for i in array_list:
    print(type(i))


<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

In [5]:
array_list = np.array(object = list_, dtype = int)
array_list

array([1, 2, 3, 4, 5])

In [6]:
array_list.dtype

dtype('int32')

In [7]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [8]:
for i in array_list:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


Yes there is the change of the data type of the array_list. It changes to numpy.str to numpy.int32

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [10]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

print(num_array.shape)
print(num_array.size)

(2, 3)
6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [17]:
matrix = np.zeros((3,3),dtype='int32')
matrix

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [20]:
ide = np.eye(5,dtype='int32')
ide

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])